.pragma library

var defaults = {
    enabled: true,
    preset: "Balanced",
    debugLogging: false,
    reseedRequest: "",
    clockMode: "Off",
    clockScale: 1.00,
    cellSize: 10,
    tps: 3,
    stepsPerFrame: 1,
    wrapEdges: true,
    ruleString: "B3/S23",
    initialDensity: 0.50,
    autoInject: true,
    injectIntervalMs: 2000,
    minAliveRatio: 0.20,
    rarePatternChance: 0.10,
    forcedInjectChance: 0.10,
    injectorMode: "Mixed",
    categoryWeights: "{\"gliders\":1.1,\"spaceships\":1.0,\"methuselahs\":0.8,\"oscillators\":0.6,\"guns\":0.12,\"still_lifes\":0.25}",
    enabledCategories: "gliders,spaceships,methuselahs,oscillators,guns,still_lifes",
    maxPatternSize: 96,
    allowLargePatterns: false,
    previewPatternId: "glider",
    cursorDrawEnabled: true,
    cursorBrushSize: 2,
    palette: "Calm Dark",
    aliveColor: "#50C878",
    deadColor: "#1A1A1A",
    backgroundColor: "#1A1A1A",
    cellShape: "Go Board",
    dyingFadeEnabled: false,
    photosensitiveSafe: false,
    safeContrast: 0.78,
    safeSaturation: 0.50,
    safeUltraLowTpsEnabled: false,
    safeUltraLowTps: 0.50,
    simDownscale: 1,
    syncFpsWithTps: true,
    maxFps: 60,
    pauseWhenHidden: false
};

var practicalPresetOrder = ["Quiet", "Balanced", "Lively", "Showcase"];

var practicalPresets = {
    "Quiet": {
        cellSize: 12,
        tps: 1,
        stepsPerFrame: 1,
        initialDensity: 0.30,
        injectIntervalMs: 3000,
        minAliveRatio: 0.18,
        rarePatternChance: 0.06,
        forcedInjectChance: 0.06,
        simDownscale: 2,
        syncFpsWithTps: true,
        maxFps: 30,
        pauseWhenHidden: true,
        photosensitiveSafe: true,
        safeContrast: 0.72,
        safeSaturation: 0.45,
        safeUltraLowTpsEnabled: false,
        safeUltraLowTps: 0.70,
        clockScale: 0.75
    },
    "Balanced": {
        cellSize: 10,
        tps: 3,
        stepsPerFrame: 1,
        initialDensity: 0.50,
        injectIntervalMs: 2000,
        minAliveRatio: 0.20,
        rarePatternChance: 0.10,
        forcedInjectChance: 0.10,
        simDownscale: 1,
        syncFpsWithTps: true,
        maxFps: 60,
        pauseWhenHidden: false,
        photosensitiveSafe: false,
        safeContrast: 0.78,
        safeSaturation: 0.50,
        safeUltraLowTpsEnabled: false,
        safeUltraLowTps: 0.99,
        clockScale: 1.00
    },
    "Lively": {
        cellSize: 8,
        tps: 6,
        stepsPerFrame: 1,
        initialDensity: 0.65,
        injectIntervalMs: 1300,
        minAliveRatio: 0.22,
        rarePatternChance: 0.12,
        forcedInjectChance: 0.12,
        simDownscale: 1,
        syncFpsWithTps: true,
        maxFps: 75,
        pauseWhenHidden: false,
        photosensitiveSafe: false,
        safeContrast: 0.78,
        safeSaturation: 0.50,
        safeUltraLowTpsEnabled: false,
        safeUltraLowTps: 0.99,
        clockScale: 1.25
    },
    "Showcase": {
        cellSize: 7,
        tps: 9,
        stepsPerFrame: 2,
        initialDensity: 0.80,
        injectIntervalMs: 900,
        minAliveRatio: 0.25,
        rarePatternChance: 0.16,
        forcedInjectChance: 0.14,
        simDownscale: 1,
        syncFpsWithTps: true,
        maxFps: 120,
        pauseWhenHidden: false,
        photosensitiveSafe: false,
        safeContrast: 0.80,
        safeSaturation: 0.55,
        safeUltraLowTpsEnabled: false,
        safeUltraLowTps: 0.99,
        clockScale: 1.50
    }
};
